package com.nexa.pipe

import android.util.Log

object IrohProxy {
    private const val TAG = "IrohProxy"
    private var nativeLoaded = false

    init {
        try {
            System.loadLibrary("nexapipe_client")
            nativeInit()
            nativeLoaded = true
            Log.d(TAG, "Native library loaded successfully")
        } catch (e: UnsatisfiedLinkError) {
            Log.e(TAG, "Failed to load native library: ${e.message}", e)
            nativeLoaded = false
        }
    }

    fun isNativeLoaded(): Boolean {
        return nativeLoaded
    }

    private external fun nativeInit(): Int

    /**
     * Injects the list of system DNS servers (comma-separated IPs, e.g.
     * "192.168.1.1,8.8.8.8"). Must be called before nativeStartIroh.
     *
     * By default iroh fails to read the system DNS on Android through JNI and
     * falls back to Google DNS, which is unreliable behind restrictive
     * networks. Kotlin reads the system DNS from ConnectivityManager and
     * injects it here; nativeStartIroh then builds a DnsResolver from it,
     * bypassing iroh's broken JNI path.
     */
    external fun nativeSetDnsServers(dnsServers: String): Int

    /**
     * Injects pre-resolved IPs for iroh infrastructure domains, in the form
     * "domain=ip1,ip2;domain2=ip3,ip4". Must be called before nativeStartIroh.
     *
     * The Great Firewall (GFW) drops UDP DNS responses for iroh.link domains,
     * so iroh's internal hickory resolver times out on dns.iroh.link and
     * *.relay.n0.iroh.link. Kotlin pre-resolves those domains with the system
     * DNS (InetAddress, which may go through DoT / Private DNS and bypass the
     * GFW) and injects the result here; nativeStartIroh builds an
     * OverrideResolver that returns the pre-resolved IPs directly for these
     * domains.
     */
    external fun nativeSetDnsOverride(overrides: String): Int

    /**
     * Configures the relay mode and the custom relay URL.
     * relayMode: "default" (use the default N0 relays), "disabled" (relay
     *            disabled, direct connections only), "custom" (custom URL).
     * relayUrl:  only used when relayMode="custom"; must be a full relay URL.
     * Must be called before nativeStartIroh.
     */
    external fun nativeSetRelayConfig(relayMode: String, relayUrl: String): Int

    /**
     * Configures the client-side 2FA credentials.
     * clientId:  must match the ID configured in the server's [auth.clients].
     * secret:    Base32-encoded TOTP key (generated by `nexapipe --generate-2fa`).
     * algorithm: "sha1" / "sha256" / "sha512".
     * Must be called before nativeStartProxy / nativeStartProxyLegacy.
     */
    external fun nativeSetTwoFactor(clientId: String, secret: String, algorithm: String): Int

    external fun nativeStartIroh(): String?

    external fun nativeStartProxy(listenPort: Int): Int

    /**
     * Pre-connect (warm-up): establish one iroh connection per configured
     * backend and cache it in the shared connection pool, so the first real
     * request after the VPN is up does not wait for the QUIC/relay handshake.
     * The TUN proxy and the local proxy share the same EndpointGroup / pool.
     * Must be called after nativeStartProxy and before the VPN is established.
     * @return number of backends warmed, or -1 on failure.
     */
    external fun nativePreconnect(): Int

    external fun nativeStartProxyLegacy(listenPort: Int, targetEndpointId: String): Int

    external fun nativeStopProxy(): Int

    external fun nativeAddNode(nodeId: String, domains: String): Int

    external fun nativeAddDomainMapping(domain: String, nodeId: String): Int

    external fun nativeRemoveNode(nodeId: String): Int

    external fun nativeClearNodes(): Int

    external fun nativeAddDomain(domain: String): Int

    external fun nativeRemoveDomain(domain: String): Int

    external fun nativeDestroy(): Int

    /**
     * Starts the TUN proxy: smoltcp handles the TCP/UDP traffic of the TUN fd
     * on the Rust side.
     *
     * Must be called after nativeStartProxy (the endpoint_group exists) and
     * after the VPN has been established. Kotlin transfers fd ownership to Rust
     * through ParcelFileDescriptor.detachFd(); Rust duplicates it (read/write)
     * and then closes the original fd.
     *
     * @param tunFd raw fd returned by ParcelFileDescriptor.detachFd()
     * @param proxyDomains comma-separated list of proxied domains
     * @return 0 on success, -1 on failure
     */
    external fun nativeStartTunProxy(
        tunFd: Int,
        proxyDomains: String
    ): Int

    /**
     * Stops the TUN proxy: aborts all background tasks and closes the
     * duplicated fds. Called by NexaVpnService.stopVPN() before the TUN fd is
     * closed.
     */
    external fun nativeStopTunProxy(): Int
}
